# Generated by Django 4.1.1 on 2024-05-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_clientdetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='f3ac1925', max_length=8, unique=True),
        ),
    ]
